[features]
seeds = false
skip-lint = false

[programs.devnet]
todo_list_app = "8TqiF764FoFH5iukG9hApRRk3gnaqgm3UCYAczRK6GB3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
